feat(lazy-imports-import): add options.async
Polymer/lazy-imports pull request #43
Opened 2017-12-04 13:42 UTC by AliMD

I use `lazy-import` in production mode and need to import multi-component asynchronously to fix our loading issue.
Could you please merge this PR as soon as possible?
Thank you.

Fixed #42

2017-12-04 14:50 UTC, stramel commented
Before this can be merged, it will need tests and docs. Also, I think instead of adding another `options &&` piece of code, we will probably want to default the `options` to an empty object. `options = options || {};`. 

Also, if you need it quickly, I suggest using your fork of it. It sometimes takes a while to get things through on here.

2017-12-05 07:20 UTC, AliMD commented
@stramel your tips applied please review it again.
Thank you.

2017-12-05 07:21 UTC, AliMD commented
Do you permit me to add separate PR for update code to main ES6 features?
Or it must remain in ES3

2017-12-05 15:21 UTC, stramel commented
@AliMD No, the core implementation and behavior must be ES5. The mixin is allowed to be written in ES6 but the mixin and behavior are just wrappers around the core implementation.

2017-12-05 15:21 UTC, stramel requested changes
Tests and Docs are still missing.

2018-01-17 07:55 UTC, AliMD commented
close because #45

2018-01-17 07:56 UTC, closed without merging